---
# file handlers/main.yaml

- name: Restart Samba
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: "{{ item }}"
    state: "{{ samba_restart_handler_state }}"
  loop: "{{ samba_services }}"
  when:
    - samba_service_mgr == "systemd"
